//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovHack.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildCareOperations
    {
        public string ChildCareKey { get; set; }
        public double LocationId { get; set; }
        public string AgeGroup { get; set; }
        public Nullable<decimal> HourlyPrice { get; set; }
        public Nullable<decimal> DailyPrice { get; set; }
    }
}
