//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovHack.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public string LOCATION_NAME { get; set; }
        public Nullable<double> TSN { get; set; }
        public Nullable<double> X_COORD { get; set; }
        public Nullable<double> Y_COORD { get; set; }
        public Nullable<double> EFA_ID { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public bool IsTrain { get; set; }
        public bool Bus { get; set; }
        public bool Lift { get; set; }
        public bool Wheelchairaccessible { get; set; }
    }
}
